version: '3'

services:

  db:
    image: postgres:13.10
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: abramenkova07/foodgram_backend:latest
    volumes:
      - static:/app/static/
      - media:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db
    env_file:
      - .env

  frontend:
    image: abramenkova07/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - static:/var/html/static/
      - media:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend

volumes:
  static:
  media:
  postgresql_data:
  redoc: