version: '3'

services:

  db:
    image: postgres:13.10
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      - .env

  backend:
    image: abramenkova07/foodgram_backend:latest
    restart: always
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    env_file:
      - .env

  nginx:
    env_file: .env
    image: abramenkova07/foodgram_nginx:latest
    restart: always
    ports:
      - 7000:80
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - backend

volumes:
  static:
  media:
  postgresql_data: