version: '3'
volumes:
  postgresql_data:
  static:
  media:
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  backend:
    image: abramenkova07/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  nginx:
    env_file: .env
    image: abramenkova07/foodgram_nginx:latest
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - backend
    ports:
      - 9090:80