version: '3'

volumes:
  postgresql_data:
  static:
  media:
  redoc:

services:

  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  backend:
    image: abramenkova07/foodgram_backend:latest
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
      - redoc:/app/api/docs/
    depends_on:
      - db

  frontend:
    image: abramenkova07/foodgram_frontend:latest
    volumes:
      - ./frontend/:/app/result_build/


  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - static:/var/html/static/
      - media:/var/html/media/
      - redoc:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
