version: '3'

services:

  db:
    image: postgres:13.10
    volumes:
      - postgresql_data:/var/lib/postgresql/data/
    env_file:
      - .env
    networks:
       - foodgram-net

  backend:
    image: abramenkova07/foodgram_backend:latest
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
    env_file:
      - .env
    networks:
       - foodgram-net

  nginx:
    env_file: .env
    image: abramenkova07/foodgram_nginx:latest
    ports:
      - 9090:80
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - backend
    networks:
       - foodgram-net

volumes:
  static:
  media:
  postgresql_data: