version: '3'

volumes:
  postgresql_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - postgresql_data:/var/lib/postgresql/data
  backend:
    image: abramenkova07/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    depends_on:
      - db
  frontend:
    env_file: .env
    image: abramenkova07/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
  gateway:
    image: abramenkova07/foodgram_nginx
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media
    depends_on:
      - backend
      - frontend
    ports:
      - 9090:80
      