# Generated by Django 3.2.3 on 2024-04-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240405_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredienttorecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Количество'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ingredienttorecipe',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient', verbose_name='Ингредиент'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='recipes.IngredientToRecipe', to='recipes.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
