# Generated by Django 3.2.3 on 2024-04-07 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20240407_2242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RecipesIngredient',
        ),
    ]
