# Generated by Django 4.2.11 on 2024-04-08 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Название необходимо писать с большой буквы.', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(help_text='Название необходимо писать с большой буквы.', max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(help_text='Цвет должен быть представлен в формате HEX (например, #ff0000).', max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Код цвета не соответствует формату HEX.', regex='^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$')], verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='Название необходимо писать с большой буквы.', max_length=200, verbose_name='Название'),
        ),
    ]
