# Generated by Django 4.2.11 on 2024-04-10 07:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_favorite_unique_user_recipe_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredienttorecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Количество'),
        ),
    ]
