# Generated by Django 4.2.11 on 2024-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_ingredienttorecipe_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favorite',
            options={'default_related_name': 'favorites', 'ordering': ('user',), 'verbose_name': 'любимый рецепт', 'verbose_name_plural': 'любимые рецепты'},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'default_related_name': 'shopping_carts', 'ordering': ('user',), 'verbose_name': 'рецепт в корзине покупок', 'verbose_name_plural': 'рецепты в корзине покупок'},
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name'], name='recipes_rec_name_891f25_idx'),
        ),
    ]
