# Generated by Django 4.2.11 on 2024-04-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_alter_ingredienttorecipe_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ingredienttorecipe',
            name='unique_ingredient_amount',
        ),
        migrations.AddConstraint(
            model_name='ingredienttorecipe',
            constraint=models.UniqueConstraint(fields=('id', 'ingredient', 'amount'), name='unique_id_ingredient_amount'),
        ),
    ]
